### ISSUE TITLE
DC pages have changed

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/WARN#238]
The DC WARN pages appear to have changed. Scraper is raising the below error. Current status of the WARN pages listed on the [2021 page](https://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications-2021) are:

* 2021-2018 work
* 2017 and earlier are broken, except for 2014, which appears to duplicate the 2018 data

- [ ] We should call the DC [Dept. of Employment Services](https://does.dc.gov/page/media-inquiries-2) about the status of their WARN pages. 
- [ ] We'll need to update the scraper based on their response. If they do not respond, we should update the scraper to only pull data for 2018 to present

## Stacktrace

```
Traceback (most recent call last):
  File "/Users/tumgoren/code/stanford/biglocal/WARN/warn/cli.py", line 67, in main
    runner.scrape(state)
  File "/Users/tumgoren/code/stanford/biglocal/WARN/warn/runner.py", line 46, in scrape
    output_csv = state_mod.scrape(self.output_dir, self.working_dir)
  File "/Users/tumgoren/code/stanford/biglocal/WARN/warn/scrapers/dc.py", line 43, in scrape
    for url in url_list:
IndexError: list index out of range


```

**Comment by zstumgoren** [comment]
Left a voice message at media inquiry number (202) 671-1904 and sent email to does@dc.gov

**Comment by zstumgoren** [comment]
DC has been removed from the list of states to scrape in Prefect, pending feedback from DC Dept of Employment Services and final implementation of bugfix.

**Comment by zstumgoren** [comment]
Followed up with DOES contacts via phone and email and tried various other departments. No luck so far.

Discovered that DC has American Jobs Center locations. They don't appear to post data on the DC job center site, but they may be a better starting point to locate whoever manages the data for DC. See below links for details and contact info:

* [American Job Center contacts page](https://www.dcnetworks.org/vosnet/ContactUs.aspx?tab=4)
* [DOES contact page](https://does.dc.gov/page/frequently-requested-contact-information)

**Comment by zstumgoren** [comment]
Reached out to mayor's office. Person there took info and said they'd have someone from DC Comms dept reach out...

**Comment by zstumgoren** [comment]
Got a callback from James Clopton in Rapid Response department. He's in charge of notifying the site maintainers in pubilc affairs dept about updated data. He notified them of the breakages and said he'd pass my info along.

**Comment by zstumgoren** [comment]
No fixes have been applied yet. Pinged James Clopton today. Awaiting response...

**Comment by zstumgoren** [comment]
Our agency contact reached to say they're finalizing updates to the pages prior to publishing. No official ETA, but sounds like we're getting closer...

**Comment by zstumgoren** [comment]
DC data pages are now restored for [2012](https://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications-2) through a newly posted [2022](https://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications-2022) page. **However**,  2014 still points to the [2018 page](https://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications-0).

> Also worth noting: The URL patterns remain all over the place (i.e. no regular pattern), so we'll need to scrape links from most recently available year.

I've notified the agency but I think we could update scrapers to start scraping from 2015 onward for now until the 2014 issue is resolved. 

/cc @palewire

**Comment by chriszs** [comment]
On a 2017 copy of the page in Archive.org, the URL 2014 now points to redirects to a [URL specific to 2014](https://web.archive.org/web/20170210010137/http://does.dc.gov/page/industry-closings-and-layoffs-warn-notifications-closure%202014), but it appears to be no longer available at that URL.

**Comment by zstumgoren** [comment]
@chriszs Latest from DC contact:

> It seems there may be more [pages?] dropping off. That [2014] page was lost in conversion and unrecoverable. I am waiting on feedback, but will follow up when I find out. Thanks and have a great weekend!

I'll pass along the Archive.org page you uncovered. Perhaps they can restore it from that page if they can confirm the accuracy of notices listed there...
